image_set_loader:
  train:
    image_set: ../data/VOC2011/ImageSets/Segmentation/train.txt
    image_dir: ../data/VOC2011/JPEGImages/
    label_dir: ../data/VOC2011/SegmentationClass
    target_size:
      - 214
      - 204
    image_format: 'jpg'
    color_mode: 'rgb'
    label_format: 'png'
  val:
    image_set: ../data/VOC2011/ImageSets/Segmentation/val.txt
    image_dir: ../data/VOC2011/JPEGImages/
    label_dir: ../data/VOC2011/SegmentationClass
    target_size:
      - 222
      - 223
    image_format: 'jpg'
    color_mode: 'rgb'
    label_format: 'png'
  test:
    image_set: ../data/VOC2011/ImageSets/Segmentation/test.txt
    image_dir: ../data/VOC2011/JPEGImages/
    label_dir: ../data/VOC2011/SegmentationClass
    target_size:
      - 224
      - 223
    image_format: 'jpg'
    color_mode: 'rgb'
    label_format: 'png'
___
ason:
  ip: &ip2 192.2.123.34
  name: *ip2